### ISSUE TITLE
Unauthenticated user should get redirected to login rather than 403

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/MetaCI#445] opened 2019-06-07 21:03 UTC
I get regular reports, usually from new users, of 403 pages trying to get to a private build that their user has access to but they aren't currently authenticated.  We should be redirecting them to the login page if unauthenticated and only throwing a 403 to authenticated users.

**Comment by davisagli** [comment] 2019-06-07 21:32
Duplicate of #282

**Closed by davisagli** 2019-06-07 21:32 UTC
